development:
  adapter: mysql2
  encoding: utf8
  database: project_clap_development
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

# production:
#   adapter: mysql2
#   encoding: utf8
#   database: project_clap_production
#   pool: 5
#   username: root
#   password:
#   socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  database: project_clap_test
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock